### ISSUE TITLE
cors issue

### ISSUE THREAD

**Issue by step21** [davidguttman/video-download-tool-server#2]
Hey,
so once deployed, it seems to be blocked by chrome cors protection.
```
Access to fetch at 'https://loady-moady.herokuapp.com/video?ytUrl=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DD6V85qfsu3g' from origin 'https://videodownloadtool.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Is this to be expected? The most obvious solution might be to just load the UI from the same place?

**Comment by step21** [comment]
Is there something I could test to investigate?

**Comment by davidguttman** [comment]
@step21 ok, figured it out. Seems like the 1-click Heroku deploy wouldn't always do the Docker install and that was causing an error. I just fixed it so if you do a fresh [1-click deploy](https://heroku.com/deploy?template=https://github.com/davidguttman/video-download-tool-server) you should be good. Let me know if not.
